### ISSUE TITLE
jasmine tests not running on linux

### ISSUE THREAD

**Issue by seemajune** [learn-co-students/intro-to-debugging.js-v-000#36]
@pletcher :

student using linux cannot run jasmine tests: output from learn -b:

 1: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome: not found

`sh: 1: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome: not found`

**Comment by pletcher** [comment]
@seemajune This was resolved, right? What did the resolution look like?

**Comment by tjnz** [comment]
run gem update learn-co then the -b flag  should work

**Comment by tyleresmith** [comment]
Having a similar problem, even after updating the gem. Using the Learn IDE on Windows 10
`sh: 1: google-chrome: not found`

**Comment by pletcher** [comment]
@tyleresmith do you have Chrome installed?

**Comment by tyleresmith** [comment]
@pletcher sure do

**Comment by pletcher** [comment]
Hm, cool cool. (I figured, but just wanted to make sure :) )

I'll dig into this ASAP -- will keep you posted!

**Comment by PeterBell** [comment]
Hey @pletcher what was the resolution to this - especially for students using the IDE? Is this something that works?  cc @AnnJohn

**Comment by pletcher** [comment]
This won't work in the IDE -- I misread @tyleresmith's comment, it seems like -- `google-chrome` was trying to execute on the remote server, which won't work.

This lab in particular requires a substantial makeover to make it IDE-compatible. I'll see where we can fit it in.

**Comment by thegands** [comment]
is there a solution for this issue? i'm running a VirtualBox VM of linux mint with google chrome installed as the default browser and i cannot get any of the tests to pass even though i followed the instructions.

**Comment by pletcher** [comment]
I had to completely rewrite this lab and work out a new testing solution that also worked with the IDE. New stuff should be deployed; it's also here: https://github.com/learn-co-students/javascript-intro-to-debugging-v-000
